version: '3'
services: 
  api: 
    build: 
      context: ./api
    container_name: api
    image: public.ecr.aws/b5z0i1v6/app-api
    ports: 
      - "3000:3000"
  ui: 
    build: 
      context: ./ui
    container_name: ui
    image: public.ecr.aws/b5z0i1v6/app-ui
    ports: 
      - "4200:4200"
  nginx: 
    build:
      context: ./nginx
    container_name: nginx
    depends_on: 
      - ui
      - api
    image: public.ecr.aws/b5z0i1v6/app-nginx
    ports: 
      - "80:80"
    
